const organizationOptions = [
  {
    value: 'AAR_JAPAN',
    label: 'AAR-Japan ',
    title: 'Association for Aid and Relief, Japan',
  },
  { value: 'ACEM', label: 'ACEM ', title: 'Afro-Canadian Evangelical Mission' },
  { value: 'ACF_USA', label: 'ACF-USA ', title: 'Action Against Hunger USA' },
  { value: 'ACM', label: 'ACM ', title: 'Akot Christian Ministries' },
  { value: 'ACROSS', label: 'ACROSS ', title: 'ACROSS' },
  {
    value: 'ACTED',
    label: 'ACTED ',
    title: 'Agency for Technical Cooperation and Development',
  },
  { value: 'ADA', label: 'ADA ', title: 'Africa Development Aid' },
  {
    value: 'ADCORD',
    label: 'ADCORD ',
    title: 'Advocate Coalition for Rights and Development',
  },
  {
    value: 'AID',
    label: 'AID ',
    title: 'Anglican International Development for Relief Change',
  },
  {
    value: 'AMREF',
    label: 'AMREF ',
    title: 'Amref Health Africa in South Sudan',
  },
  { value: 'ARC', label: 'ARC ', title: 'American Refugee Committee' },
  { value: 'ARC_IFRC', label: 'ARC-IFRC ', title: 'Austrian Red Cross' },
  { value: 'ARD_AFRICA', label: 'ARD-Africa ', title: 'ARD-Africa' },
  {
    value: 'ASCDA',
    label: 'ASCDA ',
    title: 'Aweil South Community Development Agency',
  },
  {
    value: 'ASCO',
    label: 'ASCO ',
    title: 'Aid Support Community Organization',
  },
  { value: 'ASHI', label: 'ASHI ', title: 'Alaska Sudan Health Initiative' },
  { value: 'ASIMO', label: 'ASIMO ', title: 'ASIMO South Sudan' },
  { value: 'ASMP', label: 'ASMP ', title: 'Alaska Sudan Medical Project' },
  {
    value: 'AWODA',
    label: 'AWODA ',
    title: 'Aweil Window of Opportunities and Development Agency',
  },
  {
    value: 'BEDN',
    label: 'BEDN ',
    title: 'Basic Education and Development Network',
  },
  {
    value: 'BMZ',
    label: 'BMZ ',
    title: 'German Federal Ministry for Economic Cooperation and Development',
  },
  { value: 'CAD', label: 'CAD ', title: 'Community Aid for Development' },
  {
    value: 'CADA',
    label: 'CADA ',
    title: 'Community Agribusiness Development Agency',
  },
  { value: 'CADO', label: 'CaDO ', title: 'Catholic Development Office' },
  {
    value: 'CAFOD',
    label: 'CAFOD ',
    title: 'Catholic Agency for Overseas Development',
  },
  { value: 'CAO', label: 'CAO ', title: 'Community Action Organization' },
  {
    value: 'CARD',
    label: 'CARD ',
    title: 'Community Aid for Relief and Development',
  },
  { value: 'CARE', label: 'CARE ', title: 'CARE International' },
  { value: 'CARITAS_CH', label: 'Caritas-CH ', title: 'Caritas Switzerland' },
  { value: 'CASS', label: 'CASS ', title: 'Children Aid South Sudan' },
  {
    value: 'CCOSS',
    label: 'CCOSS ',
    title: 'Care for Children and Old Age in South Sudan',
  },
  {
    value: 'CDEIP',
    label: 'CDEIP ',
    title: 'Community Development and Empowerment Initiative Program',
  },
  { value: 'CDOR', label: 'CDoR ', title: 'Caritas Diocese of Rumbek' },
  {
    value: 'CEDS',
    label: 'CEDS ',
    title: 'Centre for Emergency and Development Support',
  },
  { value: 'CEI', label: 'CEI ', title: 'Community Empowerment Initiative' },
  { value: 'CH', label: 'CH ', title: 'Coalition for Humanity' },
  {
    value: 'CHIDDO',
    label: 'CHIDDO ',
    title: "Child's Destiny And Development Organization",
  },
  { value: 'CHO', label: 'CHO ', title: 'Child Hope Organization' },
  { value: 'CLAC', label: 'CLAC ', title: 'Community Last Cry' },
  { value: 'CMC', label: 'CMC ', title: 'Charity Mission Corps' },
  { value: 'CMD', label: 'CMD ', title: 'Christian Mission for Development' },
  { value: 'CONCERN', label: 'Concern ', title: 'Concern Worldwide' },
  {
    value: 'CORDAID',
    label: 'Cordaid ',
    title: 'Catholic Organisation for Relief and Development Aid',
  },
  {
    value: 'CRADA',
    label: 'CRADA ',
    title: 'Christian Recovery and Development Agency',
  },
  { value: 'CRS', label: 'CRS ', title: 'Catholic Relief Services' },
  { value: 'DAYSTAR', label: 'DayStar ', title: 'DayStar' },
  { value: 'DORCAS', label: 'Dorcas ', title: 'Dorcas' },
  {
    value: 'DORD',
    label: 'DORD ',
    title: 'Dak Organization for Recovery and Development',
  },
  { value: 'DRC', label: 'DRC ', title: 'Danish Refugee Council' },
  { value: 'DWS', label: 'DWS ', title: 'Directorate of Water and Sanitation' },
  { value: 'EAAD', label: 'EAAD ', title: 'East African Aquatech Drilling' },
  {
    value: 'ECHO',
    label: 'ECHO ',
    title: 'EU Civil Protection and Humanitarian Aid Operations',
  },
  { value: 'EDA', label: 'EDA ', title: 'Episcopal Development Aid' },
  { value: 'EED', label: 'EED ', title: 'EED' },
  {
    value: 'FADA',
    label: 'FADA ',
    title: 'Food & Agriculture Development Agency',
  },
  { value: 'FH', label: 'FH ', title: 'Food for The Hungry' },
  { value: 'GAA', label: 'GAA ', title: 'German Agro Action' },
  { value: 'GBI', label: 'GBI ', title: 'Green Belt Initiative' },
  { value: 'GFFO', label: 'GFFO ', title: 'German Federal Foreign Office' },
  { value: 'GLI', label: 'GLI ', title: 'Great Lakes Initiative' },
  { value: 'GOAL', label: 'GOAL ', title: 'GOAL Global' },
  {
    value: 'GREDO',
    label: 'GREDO ',
    title: 'Grassroot Empowerement & Development Organization',
  },
  { value: 'HAA', label: 'HAA ', title: 'Health Action Aid' },
  {
    value: 'HACO',
    label: 'HACO ',
    title: 'Human Aid for Community Organization',
  },
  {
    value: 'HACT',
    label: 'HACT ',
    title: 'Humanitarian Aid for Change and Transformation',
  },
  {
    value: 'HCAWF',
    label: 'HCAWF ',
    title: 'Hope for Children and Women Foundation',
  },
  { value: 'HELP', label: 'HELP ', title: 'Hilfe zur Selbsthilfe e.V.' },
  { value: 'IAS', label: 'IAS ', title: 'International Aid Services' },
  {
    value: 'ICCO',
    label: 'ICCO ',
    title: 'International Organization for Development Cooperation',
  },
  { value: 'IHO', label: 'IHO ', title: 'Impact Health Organization' },
  { value: 'IM', label: 'IM ', title: 'MENTOR Initiative' },
  {
    value: 'INTENT',
    label: 'INTENT ',
    title: 'Integrated Humanitarian Network for Transformation',
  },
  {
    value: 'INTERSOS',
    label: 'INTERSOS ',
    title: 'INTERSOS Humanitarian Aid Organization',
  },
  {
    value: 'IOM',
    label: 'IOM ',
    title: 'International Organization for Migration',
  },
  { value: 'IRC', label: 'IRC ', title: 'International Rescue Committee' },
  { value: 'IRW', label: 'IRW ', title: 'Islamic Relief Worldwide' },
  {
    value: 'JICA',
    label: 'JICA ',
    title: 'Japan International Cooperation Agency',
  },
  {
    value: 'LCED',
    label: 'LCED ',
    title: 'Lacha Community and Economic Development',
  },
  { value: 'LIVEWELL', label: 'LiveWell ', title: 'LiveWell' },
  {
    value: 'MACDA',
    label: 'MaCDA ',
    title: 'Mother and Children Development Aid',
  },
  { value: 'MC', label: 'MC ', title: 'Mercy Corps' },
  { value: 'MCO', label: 'MCO ', title: 'Mercy Charity Organisation' },
  { value: 'MEDAIR', label: 'MEDAIR ', title: 'Medair' },
  { value: 'MI', label: 'MI ', title: 'Malteser International' },
  {
    value: 'MOPI_JONGLEI',
    label: 'MoPI-Jonglei ',
    title: 'Ministry of Physical Infrastructure (Jonglei State)',
  },
  { value: 'NCA', label: 'NCA ', title: 'Norwegian Church Aid' },
  { value: 'NH', label: 'NH ', title: 'Nile Hope' },
  { value: 'NPA', label: 'NPA ', title: "Norwegian People's Aid" },
  { value: 'NRC', label: 'NRC ', title: 'Norwegian Refugee Council' },
  {
    value: 'NSDO',
    label: 'NSDO ',
    title: 'Nile Sustainable Development Organization',
  },
  { value: 'NURTURE', label: 'NURTURE ', title: 'Nurture South Sudan' },
  { value: 'OSF', label: 'OSF ', title: 'Open Society Foundations' },
  { value: 'OXFAM', label: 'OXFAM ', title: 'Oxfam International' },
  { value: 'PACT', label: 'PACT ', title: 'Pact Inc.' },
  { value: 'PAH', label: 'PAH ', title: 'Polish Humanitarian Action' },
  { value: 'PCO', label: 'PCO ', title: 'Peace Corps Organization' },
  { value: 'PDI', label: 'PDI ', title: 'Panda Development Initiative' },
  { value: 'PLAN', label: 'PLAN ', title: 'Plan International' },
  { value: 'POH', label: 'POH ', title: 'Pilgrims of Hope Organization' },
  { value: 'PSI', label: 'PSI ', title: 'Population Services International' },
  { value: 'PWJ', label: 'PWJ ', title: 'Peace Winds Japan' },
  { value: 'RCO', label: 'RCO ', title: 'Relief Corps Organization' },
  { value: 'REACH', label: 'REACH ', title: 'REACH Initiative' },
  { value: 'RI', label: 'RI ', title: 'Relief International' },
  {
    value: 'RIPDO',
    label: 'RIPDO ',
    title: 'Rural Initiative for Peace and Development Organization',
  },
  {
    value: 'RUWASSA',
    label: 'RUWASSA ',
    title: 'Rural Water Supply and Sanitation Agency',
  },
  {
    value: 'SAADO',
    label: 'SAADO ',
    title: 'Smile Again Africa Development Organization',
  },
  { value: 'SALI', label: 'SALI ', title: 'Save a Life International' },
  { value: 'SALT', label: 'SALT ', title: 'SALT' },
  { value: 'SC', label: 'SC ', title: 'Save The Children' },
  {
    value: 'SCPD',
    label: 'SCPD ',
    title: 'Sobat Community for Peace and Development',
  },
  {
    value: 'SDC',
    label: 'SDC ',
    title: 'Swiss Agency for Development and Cooperation',
  },
  { value: 'SHAO', label: 'SHAO ', title: 'Stretching Hands to Africa' },
  { value: 'SI', label: 'SI ', title: 'Solidarités International' },
  {
    value: 'SIDA',
    label: 'SIDA ',
    title: 'Swedish International Development Cooperation Agency',
  },
  { value: 'SMC', label: 'SMC ', title: 'Swedish Mission Council' },
  {
    value: 'SNV',
    label: 'SNV ',
    title: 'SNV Netherlands Development Organisation',
  },
  {
    value: 'SOH',
    label: 'SoH ',
    title: 'Sign of Hope - Hoffnungszeichen e.V.',
  },
  { value: 'SP', label: 'SP ', title: "Samaritan's Purse" },
  {
    value: 'SPEDP',
    label: 'SPEDP ',
    title: 'Sudan Peace and Education Development Programme',
  },
  {
    value: 'SPOCI',
    label: 'SPOCI ',
    title: 'Stop Poverty Communal Initiative',
  },
  {
    value: 'SSDO',
    label: 'SSDO ',
    title: 'South Sudan Development Organization',
  },
  { value: 'SSHF', label: 'SSHF ', title: 'South Sudan Humanitarian Fund' },
  { value: 'SSRCS', label: 'SSRCS ', title: 'South Sudan Red Cross' },
  { value: 'SSUDA', label: 'SSUDA ', title: 'South Sudan Development Agency' },
  {
    value: 'SSUWC',
    label: 'SSUWC ',
    title: 'South Sudan Urban Water Coperation',
  },
  { value: 'SUFEM', label: 'SUFEM ', title: 'Sudanese Fellowship Mission' },
  { value: 'TDH', label: 'TDH ', title: 'Terre des hommes' },
  { value: 'TEARFUND', label: 'Tearfund ', title: 'Tearfund' },
  { value: 'TERM', label: 'TERM ', title: 'The Rescue Mission' },
  { value: 'THESO', label: 'THESO ', title: 'The Health Support Organization' },
  { value: 'TITIA', label: 'TITIA ', title: 'TITI Foundation Africa' },
  { value: 'TOP_RELIEF', label: 'Top Relief ', title: 'Top Relief' },
  { value: 'UKAID', label: 'UKAID ', title: 'UKAID' },
  {
    value: 'UMCOR',
    label: 'UMCOR ',
    title: 'United Methodist Committee on Relief',
  },
  {
    value: 'UNHCR',
    label: 'UNHCR ',
    title: 'UN High Commissioner for Refugees',
  },
  { value: 'UNICEF', label: 'UNICEF ', title: "UN Children's Fund" },
  {
    value: 'UNIDOR',
    label: 'UNIDOR ',
    title: 'Universal Intervention and Development Organisation',
  },
  {
    value: 'UNIDO_SS',
    label: 'UNIDO-SS ',
    title: 'Universal Intervention and Development Organization',
  },
  {
    value: 'UNKEA',
    label: 'UNKEA ',
    title: 'Universal Network for Knowledge & Empowerment Agency',
  },
  { value: 'USAID', label: 'USAID ', title: 'USAID' },
  {
    value: 'WECSS',
    label: 'WECSS ',
    title: 'Women Empowerment Centre South Sudan',
  },
  { value: 'WFSS', label: 'WFSS ', title: 'Water for South Sudan' },
  {
    value: 'WHEEL',
    label: 'WHEEL ',
    title: 'Wealth Health and Education for Empowered Life',
  },
  { value: 'WHH', label: 'WHH ', title: 'Welthungerhilfe' },
  { value: 'WR', label: 'WR ', title: 'World Relief' },
  { value: 'WVI', label: 'WVI ', title: 'World Vision International' },
  { value: 'WWOH', label: 'WWoH ', title: 'Wadeng Wings of Hope' },
  { value: 'ZOA', label: 'ZOA ', title: 'ZOA International' },
];

export const schemaTags: SchemaTag[] = [
  {
    value: 'documentType',
    label: 'Document Type',
    multiple: false,
    options: [
      { value: 'MAP', label: 'Map' },
      {
        value: 'TERMS_OF_REFERENCE',
        label: 'ToR',
        title: 'Terms of Reference',
      },
      { value: 'REPORT', label: 'Report' },
      { value: 'BASELINE', label: 'Baseline', title: 'Baseline Assessment' },
      { value: 'ASSESSMENT', label: 'Assessment' },
      { value: 'FACTSHEET', label: 'Factsheet' },
      { value: 'DATA', label: 'Data' },
      { value: 'ODK_TOOL', label: 'Tool' },
    ],
  },
  {
    value: 'fileType',
    label: 'File Type',
    multiple: false,
    options: [
      { value: 'PDF', label: 'PDF' },
      { value: 'DOCX', label: 'Word' },
      { value: 'XLSX', label: 'Excel' },
      { value: 'PPTX', label: 'PowerPoint' },
      { value: 'CSV', label: 'CSV' },
      { value: 'ZIP', label: 'ZIP' },
    ],
  },
  {
    value: 'clusters',
    label: 'Clusters',
    multiple: true,
    options: [
      {
        value: 'CCCM',
        label: 'CCCM',
        title: 'Camp Coordination and Camp Management',
      },
      { value: 'EDUCATION', label: 'Education' },
      { value: 'FSL', label: 'FSL', title: 'Food Security & Livelihoods' },
      { value: 'HEALTH', label: 'Health' },
      { value: 'LOGISTICS', label: 'Logistics' },
      { value: 'NUTRITION', label: 'Nutrition' },
      { value: 'PROTECTION', label: 'Protection' },
      { value: 'SHELTER', label: 'Shelter' },
    ],
  },
  {
    value: 'washTypes',
    label: 'WASH Types',
    multiple: true,
    options: [
      { value: 'WATER', label: 'Water' },
      { value: 'SANITATION', label: 'Sanitation' },
      { value: 'HYGIENE', label: 'Hygiene' },
    ],
  },
  {
    value: 'organizations',
    label: 'Organizations',
    multiple: true,
    options: organizationOptions,
  },
  {
    value: 'donors',
    label: 'Donors',
    multiple: true,
    options: organizationOptions,
  },
];

export const schemaAdmin: SchemaAdmin = {
  admin0: [{ value: 'SS', label: 'South Sudan' }],
  admin1: [
    { admin0: 'SS', value: 'SS01', label: 'Central Equatoria' },
    { admin0: 'SS', value: 'SS02', label: 'Eastern Equatoria' },
    { admin0: 'SS', value: 'SS03', label: 'Jonglei' },
    { admin0: 'SS', value: 'SS04', label: 'Lakes' },
    { admin0: 'SS', value: 'SS05', label: 'Northern Bahr el Ghazal' },
    { admin0: 'SS', value: 'SS06', label: 'Unity' },
    { admin0: 'SS', value: 'SS07', label: 'Upper Nile' },
    { admin0: 'SS', value: 'SS08', label: 'Warrap' },
    { admin0: 'SS', value: 'SS09', label: 'Western Bahr el Ghazal' },
    { admin0: 'SS', value: 'SS10', label: 'Western Equatoria' },
  ],
  admin2: [
    { admin0: 'SS', admin1: 'SS01', value: 'SS0101', label: 'Juba' },
    { admin0: 'SS', admin1: 'SS01', value: 'SS0102', label: 'Kajo-keji' },
    { admin0: 'SS', admin1: 'SS01', value: 'SS0103', label: 'Lainya' },
    { admin0: 'SS', admin1: 'SS01', value: 'SS0104', label: 'Morobo' },
    { admin0: 'SS', admin1: 'SS01', value: 'SS0105', label: 'Terekeka' },
    { admin0: 'SS', admin1: 'SS01', value: 'SS0106', label: 'Yei' },
    { admin0: 'SS', admin1: 'SS02', value: 'SS0201', label: 'Budi' },
    { admin0: 'SS', admin1: 'SS02', value: 'SS0202', label: 'Ikotos' },
    { admin0: 'SS', admin1: 'SS02', value: 'SS0203', label: 'Kapoeta East' },
    { admin0: 'SS', admin1: 'SS02', value: 'SS0204', label: 'Kapoeta North' },
    { admin0: 'SS', admin1: 'SS02', value: 'SS0205', label: 'Kapoeta South' },
    { admin0: 'SS', admin1: 'SS02', value: 'SS0206', label: 'Lafon' },
    { admin0: 'SS', admin1: 'SS02', value: 'SS0207', label: 'Magwi' },
    { admin0: 'SS', admin1: 'SS02', value: 'SS0208', label: 'Torit' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0301', label: 'Akobo' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0302', label: 'Ayod' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0303', label: 'Bor South' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0304', label: 'Canal/Pigi' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0305', label: 'Duk' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0306', label: 'Fangak' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0307', label: 'Nyirol' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0308', label: 'Pibor' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0309', label: 'Pochalla' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0310', label: 'Twic East' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0311', label: 'Uror' },
    { admin0: 'SS', admin1: 'SS04', value: 'SS0401', label: 'Awerial' },
    { admin0: 'SS', admin1: 'SS04', value: 'SS0402', label: 'Cueibet' },
    { admin0: 'SS', admin1: 'SS04', value: 'SS0403', label: 'Rumbek Centre' },
    { admin0: 'SS', admin1: 'SS04', value: 'SS0404', label: 'Rumbek East' },
    { admin0: 'SS', admin1: 'SS04', value: 'SS0405', label: 'Rumbek North' },
    { admin0: 'SS', admin1: 'SS04', value: 'SS0406', label: 'Wulu' },
    { admin0: 'SS', admin1: 'SS04', value: 'SS0407', label: 'Yirol East' },
    { admin0: 'SS', admin1: 'SS04', value: 'SS0408', label: 'Yirol West' },
    { admin0: 'SS', admin1: 'SS05', value: 'SS0501', label: 'Aweil Centre' },
    { admin0: 'SS', admin1: 'SS05', value: 'SS0502', label: 'Aweil East' },
    { admin0: 'SS', admin1: 'SS05', value: 'SS0503', label: 'Aweil North' },
    { admin0: 'SS', admin1: 'SS05', value: 'SS0504', label: 'Aweil South' },
    { admin0: 'SS', admin1: 'SS05', value: 'SS0505', label: 'Aweil West' },
    { admin0: 'SS', admin1: 'SS06', value: 'SS0601', label: 'Abiemnhom' },
    { admin0: 'SS', admin1: 'SS06', value: 'SS0602', label: 'Guit' },
    { admin0: 'SS', admin1: 'SS06', value: 'SS0603', label: 'Koch' },
    { admin0: 'SS', admin1: 'SS06', value: 'SS0604', label: 'Leer' },
    { admin0: 'SS', admin1: 'SS06', value: 'SS0605', label: 'Mayendit' },
    { admin0: 'SS', admin1: 'SS06', value: 'SS0606', label: 'Mayom' },
    { admin0: 'SS', admin1: 'SS06', value: 'SS0607', label: 'Panyijiar' },
    { admin0: 'SS', admin1: 'SS06', value: 'SS0608', label: 'Pariang' },
    { admin0: 'SS', admin1: 'SS06', value: 'SS0609', label: 'Rubkona' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0701', label: 'Baliet' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0702', label: 'Fashoda' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0703', label: 'Longochuk' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0704', label: 'Luakpiny/Nasir' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0705', label: 'Maban' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0706', label: 'Maiwut' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0707', label: 'Malakal' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0708', label: 'Manyo' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0709', label: 'Melut' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0710', label: 'Panyikang' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0711', label: 'Renk' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0712', label: 'Ulang' },
    { admin0: 'SS', admin1: 'SS08', value: 'SS0801', label: 'Gogrial East' },
    { admin0: 'SS', admin1: 'SS08', value: 'SS0802', label: 'Gogrial West' },
    { admin0: 'SS', admin1: 'SS08', value: 'SS0803', label: 'Tonj East' },
    { admin0: 'SS', admin1: 'SS08', value: 'SS0804', label: 'Tonj North' },
    { admin0: 'SS', admin1: 'SS08', value: 'SS0805', label: 'Tonj South' },
    { admin0: 'SS', admin1: 'SS08', value: 'SS0806', label: 'Twic' },
    { admin0: 'SS', admin1: 'SS08', value: 'SS0807', label: 'Abyei Region' },
    { admin0: 'SS', admin1: 'SS09', value: 'SS0901', label: 'Jur River' },
    { admin0: 'SS', admin1: 'SS09', value: 'SS0902', label: 'Raja' },
    { admin0: 'SS', admin1: 'SS09', value: 'SS0903', label: 'Wau' },
    { admin0: 'SS', admin1: 'SS10', value: 'SS1001', label: 'Ezo' },
    { admin0: 'SS', admin1: 'SS10', value: 'SS1002', label: 'Ibba' },
    { admin0: 'SS', admin1: 'SS10', value: 'SS1003', label: 'Maridi' },
    { admin0: 'SS', admin1: 'SS10', value: 'SS1004', label: 'Mundri East' },
    { admin0: 'SS', admin1: 'SS10', value: 'SS1005', label: 'Mundri West' },
    { admin0: 'SS', admin1: 'SS10', value: 'SS1006', label: 'Mvolo' },
    { admin0: 'SS', admin1: 'SS10', value: 'SS1007', label: 'Nagero' },
    { admin0: 'SS', admin1: 'SS10', value: 'SS1008', label: 'Nzara' },
    { admin0: 'SS', admin1: 'SS10', value: 'SS1009', label: 'Tambura' },
    { admin0: 'SS', admin1: 'SS10', value: 'SS1010', label: 'Yambio' },
  ],
};
