version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.10.0
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys
      - run: ssh-keyscan -H $HOSTNAME_1 >> ~/.ssh/known_hosts
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run: docker build -t impactinitiatives/apollo .
      - run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run: docker push impactinitiatives/apollo
      - run: ssh core@$HOSTNAME_1 docker stop impact-api
      - run: ssh core@$HOSTNAME_1 docker rm impact-api
      - run: >
          ssh core@$HOSTNAME_1
          docker run
          --name impact-api
          --restart=always
          -d
          -p "80:80"
          -e DATABASE_URL=$DATABASE_URL
          -e SERVER_1_AUDIENCE=$SERVER_1_AUDIENCE
          -e SERVER_1_ISSUER=$SERVER_1_ISSUER
          impactinitiatives/apollo
      - run: ssh core@$HOSTNAME_1 docker image prune -af
