export const schemaTags: SchemaTag[] = [
  {
    value: 'documentType',
    label: 'Document Type',
    multiple: false,
    options: [
      { value: 'MAP', label: 'Map' },
      {
        value: 'TERMS_OF_REFERENCE',
        label: 'ToR',
        title: 'Terms of Reference',
      },
      { value: 'REPORT', label: 'Report' },
      { value: 'ASSESSMENT', label: 'Assessment' },
      { value: 'FACTSHEET', label: 'Factsheet' },
      { value: 'DATA', label: 'Data' },
      { value: 'ODK_TOOL', label: 'ODK Tool' },
      { value: 'ADMIN', label: 'Internal Admin' },
    ],
  },
  {
    value: 'fileType',
    label: 'File Type',
    multiple: false,
    options: [
      { value: 'PDF', label: 'PDF' },
      { value: 'DOCX', label: 'Word' },
      { value: 'XLSX', label: 'Excel' },
      { value: 'PPTX', label: 'PowerPoint' },
      { value: 'CSV', label: 'CSV' },
      { value: 'ZIP', label: 'ZIP' },
    ],
  },
  {
    value: 'project',
    label: 'Project',
    multiple: false,
    options: [
      { value: 'ADMIN', label: 'Internal Admin' },
      { value: 'AOK', label: 'AoK', title: 'Area of Knowledge' },
      {
        value: 'PRM',
        label: 'Port Monitoring',
        title: 'Port and Road Monitoring',
      },
      { value: 'REFUGEE', label: 'Refugee Response' },
      {
        value: 'RAPID',
        label: 'Rapid / Ad-Hoc',
        title: 'Rapid / Ad-Hoc Assessments',
      },
      {
        value: 'SECTOR',
        label: 'Sector Specific',
        title: 'Sector Specific Assessments',
      },
      {
        value: 'AAP',
        label: 'AAP',
        title: 'Accountability to Affected Populations',
      },
    ],
  },
  {
    value: 'clusters',
    label: 'Clusters',
    multiple: true,
    options: [
      {
        value: 'CCCM',
        label: 'CCCM',
        title: 'Camp Coordination and Camp Management',
      },
      { value: 'EDUCATION', label: 'Education' },
      { value: 'FSL', label: 'FSL', title: 'Food Security & Livelihoods' },
      { value: 'HEALTH', label: 'Health' },
      { value: 'LOGISTICS', label: 'Logistics' },
      { value: 'MARKET', label: 'Market' },
      { value: 'NUTRITION', label: 'Nutrition' },
      { value: 'PROTECTION', label: 'Protection' },
      { value: 'SHELTER', label: 'Shelter' },
    ],
  },
  {
    value: 'audiences',
    label: 'Audiences',
    multiple: true,
    options: [
      { value: 'FIELD_OFFICER', label: 'Field Officer' },
      { value: 'ADMIN_OFFICER', label: 'Admin Officer' },
      { value: 'ASSESSMENT_OFFICER', label: 'Assessment Officer' },
      { value: 'GIS_OFFICER', label: 'GIS Officer' },
      { value: 'HQ_GENEVA', label: 'HQ Geneva' },
    ],
  },
];

export const schemaAdmin: SchemaAdmin = {
  admin0: [{ value: 'SS', label: 'South Sudan' }],
  admin1: [
    { admin0: 'SS', value: 'SS01', label: 'Central Equatoria' },
    { admin0: 'SS', value: 'SS02', label: 'Eastern Equatoria' },
    { admin0: 'SS', value: 'SS03', label: 'Jonglei' },
    { admin0: 'SS', value: 'SS04', label: 'Lakes' },
    { admin0: 'SS', value: 'SS05', label: 'Northern Bahr el Ghazal' },
    { admin0: 'SS', value: 'SS06', label: 'Unity' },
    { admin0: 'SS', value: 'SS07', label: 'Upper Nile' },
    { admin0: 'SS', value: 'SS08', label: 'Warrap' },
    { admin0: 'SS', value: 'SS09', label: 'Western Bahr el Ghazal' },
    { admin0: 'SS', value: 'SS10', label: 'Western Equatoria' },
  ],
  admin2: [
    { admin0: 'SS', admin1: 'SS01', value: 'SS0101', label: 'Juba' },
    { admin0: 'SS', admin1: 'SS01', value: 'SS0102', label: 'Kajo-keji' },
    { admin0: 'SS', admin1: 'SS01', value: 'SS0103', label: 'Lainya' },
    { admin0: 'SS', admin1: 'SS01', value: 'SS0104', label: 'Morobo' },
    { admin0: 'SS', admin1: 'SS01', value: 'SS0105', label: 'Terekeka' },
    { admin0: 'SS', admin1: 'SS01', value: 'SS0106', label: 'Yei' },
    { admin0: 'SS', admin1: 'SS02', value: 'SS0201', label: 'Budi' },
    { admin0: 'SS', admin1: 'SS02', value: 'SS0202', label: 'Ikotos' },
    { admin0: 'SS', admin1: 'SS02', value: 'SS0203', label: 'Kapoeta East' },
    { admin0: 'SS', admin1: 'SS02', value: 'SS0204', label: 'Kapoeta North' },
    { admin0: 'SS', admin1: 'SS02', value: 'SS0205', label: 'Kapoeta South' },
    { admin0: 'SS', admin1: 'SS02', value: 'SS0206', label: 'Lafon' },
    { admin0: 'SS', admin1: 'SS02', value: 'SS0207', label: 'Magwi' },
    { admin0: 'SS', admin1: 'SS02', value: 'SS0208', label: 'Torit' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0301', label: 'Akobo' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0302', label: 'Ayod' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0303', label: 'Bor South' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0304', label: 'Canal/Pigi' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0305', label: 'Duk' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0306', label: 'Fangak' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0307', label: 'Nyirol' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0308', label: 'Pibor' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0309', label: 'Pochalla' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0310', label: 'Twic East' },
    { admin0: 'SS', admin1: 'SS03', value: 'SS0311', label: 'Uror' },
    { admin0: 'SS', admin1: 'SS04', value: 'SS0401', label: 'Awerial' },
    { admin0: 'SS', admin1: 'SS04', value: 'SS0402', label: 'Cueibet' },
    { admin0: 'SS', admin1: 'SS04', value: 'SS0403', label: 'Rumbek Centre' },
    { admin0: 'SS', admin1: 'SS04', value: 'SS0404', label: 'Rumbek East' },
    { admin0: 'SS', admin1: 'SS04', value: 'SS0405', label: 'Rumbek North' },
    { admin0: 'SS', admin1: 'SS04', value: 'SS0406', label: 'Wulu' },
    { admin0: 'SS', admin1: 'SS04', value: 'SS0407', label: 'Yirol East' },
    { admin0: 'SS', admin1: 'SS04', value: 'SS0408', label: 'Yirol West' },
    { admin0: 'SS', admin1: 'SS05', value: 'SS0501', label: 'Aweil Centre' },
    { admin0: 'SS', admin1: 'SS05', value: 'SS0502', label: 'Aweil East' },
    { admin0: 'SS', admin1: 'SS05', value: 'SS0503', label: 'Aweil North' },
    { admin0: 'SS', admin1: 'SS05', value: 'SS0504', label: 'Aweil South' },
    { admin0: 'SS', admin1: 'SS05', value: 'SS0505', label: 'Aweil West' },
    { admin0: 'SS', admin1: 'SS06', value: 'SS0601', label: 'Abiemnhom' },
    { admin0: 'SS', admin1: 'SS06', value: 'SS0602', label: 'Guit' },
    { admin0: 'SS', admin1: 'SS06', value: 'SS0603', label: 'Koch' },
    { admin0: 'SS', admin1: 'SS06', value: 'SS0604', label: 'Leer' },
    { admin0: 'SS', admin1: 'SS06', value: 'SS0605', label: 'Mayendit' },
    { admin0: 'SS', admin1: 'SS06', value: 'SS0606', label: 'Mayom' },
    { admin0: 'SS', admin1: 'SS06', value: 'SS0607', label: 'Panyijiar' },
    { admin0: 'SS', admin1: 'SS06', value: 'SS0608', label: 'Pariang' },
    { admin0: 'SS', admin1: 'SS06', value: 'SS0609', label: 'Rubkona' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0701', label: 'Baliet' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0702', label: 'Fashoda' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0703', label: 'Longochuk' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0704', label: 'Luakpiny/Nasir' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0705', label: 'Maban' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0706', label: 'Maiwut' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0707', label: 'Malakal' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0708', label: 'Manyo' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0709', label: 'Melut' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0710', label: 'Panyikang' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0711', label: 'Renk' },
    { admin0: 'SS', admin1: 'SS07', value: 'SS0712', label: 'Ulang' },
    { admin0: 'SS', admin1: 'SS08', value: 'SS0801', label: 'Gogrial East' },
    { admin0: 'SS', admin1: 'SS08', value: 'SS0802', label: 'Gogrial West' },
    { admin0: 'SS', admin1: 'SS08', value: 'SS0803', label: 'Tonj East' },
    { admin0: 'SS', admin1: 'SS08', value: 'SS0804', label: 'Tonj North' },
    { admin0: 'SS', admin1: 'SS08', value: 'SS0805', label: 'Tonj South' },
    { admin0: 'SS', admin1: 'SS08', value: 'SS0806', label: 'Twic' },
    { admin0: 'SS', admin1: 'SS08', value: 'SS0807', label: 'Abyei Region' },
    { admin0: 'SS', admin1: 'SS09', value: 'SS0901', label: 'Jur River' },
    { admin0: 'SS', admin1: 'SS09', value: 'SS0902', label: 'Raja' },
    { admin0: 'SS', admin1: 'SS09', value: 'SS0903', label: 'Wau' },
    { admin0: 'SS', admin1: 'SS10', value: 'SS1001', label: 'Ezo' },
    { admin0: 'SS', admin1: 'SS10', value: 'SS1002', label: 'Ibba' },
    { admin0: 'SS', admin1: 'SS10', value: 'SS1003', label: 'Maridi' },
    { admin0: 'SS', admin1: 'SS10', value: 'SS1004', label: 'Mundri East' },
    { admin0: 'SS', admin1: 'SS10', value: 'SS1005', label: 'Mundri West' },
    { admin0: 'SS', admin1: 'SS10', value: 'SS1006', label: 'Mvolo' },
    { admin0: 'SS', admin1: 'SS10', value: 'SS1007', label: 'Nagero' },
    { admin0: 'SS', admin1: 'SS10', value: 'SS1008', label: 'Nzara' },
    { admin0: 'SS', admin1: 'SS10', value: 'SS1009', label: 'Tambura' },
    { admin0: 'SS', admin1: 'SS10', value: 'SS1010', label: 'Yambio' },
  ],
};
