- hosts: all
  gather_facts: no
  tasks:
    - name: Remove env
      raw: sudo rm ~/.env || true
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Copy env file to primary api
      raw: scp ../.env
        core@{{ hostvars[inventory_hostname].groups.all[0] }}:~/.env
- hosts: all
  gather_facts: no
  tasks:
    - name: Give read permission to owner only
      raw: chmod 400 ~/.env
